version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: "mental_db"
      POSTGRES_USER: "mental_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  bot:
    image: azlymoon/mental_bot:latest
    restart: always
    ports:
      - "8080:8080"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
  bot:
    driver: bridge
