version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "mental_db"
      POSTGRES_USER: "mental_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
