version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: "mental_db"
      POSTGRES_USER: "mental_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5435:5432"
