fastapi:
  debug: true
  port: 9097

db:
  HOST: 'localhost'
  PORT: 5432
  USER: mental_user
  PASSWORD: password
  DATABASE_NAME: mental_db

telegram:
  token: token

oauth:
  appid: fedded7a-a595-424d-84d4-e43db36e945e
